# Generated by Django 5.2.3 on 2025-11-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comment_delete_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='timestamp',
        ),
    ]
