# Generated by Django 5.2.3 on 2025-11-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_bid_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='picture',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
