# Generated by Django 5.2.3 on 2025-11-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='picture_content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
